/*
 * Signaleringcontroles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package nl.procura.burgerzaken.vrsclient;

import java.util.HashMap;
import java.util.Map;

public abstract class ApiClient {

  private final String baseUri;

  public ApiClient(String baseUri) {
    this.baseUri = baseUri;
  }

  /**
   * Get the base URI to resolve the endpoint paths against.
   *
   * @return The complete base URI that the rest of the API parameters are
   * resolved against.
   */
  public String getBaseUri() {
    return baseUri;
  }

  public abstract <T, R> R get(Request<T> request, Class<R> type);

  public abstract <T, R> R post(Request<T> request, Class<R> type);

  public static class Request<T> {

    public final String              path;
    public final Map<String, String> headers;
    public T                         body;

    public Request(String path) {
      this.path = path;
      this.headers = new HashMap<>();
      this.body = null;
    }

    public Request<T> header(String key, String value) {
      headers.put(key, value);
      return this;
    }

    public Request<T> body(T body) {
      this.body = body;
      return this;
    }
  }
}
