/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:29 PM CEST 
//

package nl.procura.rdw.processen.p1654.f01;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for AANVR-RYB-K-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="AANVR-RYB-K-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AUTOR-A-RYB-K" type="{}AUTOR-CODE"/>
 *         &lt;element name="GEM-LOC-A-RYB-K" type="{}GEM-LOC-CODE"/>
 *         &lt;element name="SRT-AANVR-RYB-K" type="{}SRT-AANVR-RYB-K"/>
 *         &lt;element name="GBA-BEST-IND" type="{}INDIC-JN" minOccurs="0"/>
 *         &lt;element name="RYB-NR-VERVANG" type="{}RYB-NR-LANG" minOccurs="0"/>
 *         &lt;element name="BEZORG-RYB-IND" type="{}INDIC-JN" minOccurs="0"/>
 *         &lt;element name="E-MAIL-A-BEZORG" type="{}E-MAIL-ADRES" minOccurs="0"/>
 *         &lt;element name="TEL-NR-A-BEZORG" type="{}TEL-NR-16" minOccurs="0"/>
 *         &lt;element name="REF-RYB-BEZORG" type="{}TEKST-30" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AANVR-RYB-K-GEG",
    propOrder = {

    })
public class AANVRRYBKGEG implements Serializable {

  @XmlElement(name = "AUTOR-A-RYB-K",
      required = true)
  private BigInteger autorarybk;
  @XmlElement(name = "GEM-LOC-A-RYB-K",
      required = true)
  private BigInteger gemlocarybk;
  @XmlElement(name = "SRT-AANVR-RYB-K",
      required = true)
  private BigInteger srtaanvrrybk;
  @XmlElement(name = "GBA-BEST-IND")
  private String     gbabestind;
  @XmlElement(name = "RYB-NR-VERVANG")
  private String     rybnrvervang;
  @XmlElement(name = "BEZORG-RYB-IND")
  private String     bezorgrybind;
  @XmlElement(name = "E-MAIL-A-BEZORG")
  private String     emailabezorg;
  @XmlElement(name = "TEL-NR-A-BEZORG")
  private String     telnrabezorg;
  @XmlElement(name = "REF-RYB-BEZORG")
  private String     refrybbezorg;

  public BigInteger getAutorarybk() {
    return this.autorarybk;
  }

  public void setAutorarybk(BigInteger autorarybk) {
    this.autorarybk = autorarybk;
  }

  public BigInteger getGemlocarybk() {
    return this.gemlocarybk;
  }

  public void setGemlocarybk(BigInteger gemlocarybk) {
    this.gemlocarybk = gemlocarybk;
  }

  public BigInteger getSrtaanvrrybk() {
    return this.srtaanvrrybk;
  }

  public void setSrtaanvrrybk(BigInteger srtaanvrrybk) {
    this.srtaanvrrybk = srtaanvrrybk;
  }

  public String getGbabestind() {
    return this.gbabestind;
  }

  public void setGbabestind(String gbabestind) {
    this.gbabestind = gbabestind;
  }

  public String getRybnrvervang() {
    return this.rybnrvervang;
  }

  public void setRybnrvervang(String rybnrvervang) {
    this.rybnrvervang = rybnrvervang;
  }

  public String getBezorgrybind() {
    return this.bezorgrybind;
  }

  public void setBezorgrybind(String bezorgrybind) {
    this.bezorgrybind = bezorgrybind;
  }

  public String getEmailabezorg() {
    return this.emailabezorg;
  }

  public void setEmailabezorg(String emailabezorg) {
    this.emailabezorg = emailabezorg;
  }

  public String getTelnrabezorg() {
    return this.telnrabezorg;
  }

  public void setTelnrabezorg(String telnrabezorg) {
    this.telnrabezorg = telnrabezorg;
  }

  public String getRefrybbezorg() {
    return this.refrybbezorg;
  }

  public void setRefrybbezorg(String refrybbezorg) {
    this.refrybbezorg = refrybbezorg;
  }

}
