/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:26 PM CEST 
//

package nl.procura.rdw.processen.p0188.f07;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for MAATREGEL-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="MAATREGEL-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="MAATR-VOLG-NR" type="{}MAATR-VOLG-NR" minOccurs="0"/>
 *         &lt;element name="SRT-MAATR" type="{}SRT-MAATR" minOccurs="0"/>
 *         &lt;element name="SRT-AUT-MAATR" type="{}SOORT-AUTOR" minOccurs="0"/>
 *         &lt;element name="AUTOR-C-MAATR" type="{}AUTOR-CODE-RYB" minOccurs="0"/>
 *         &lt;element name="NAAM-AUT-MAATR" type="{}NAAM-AUTOR" minOccurs="0"/>
 *         &lt;element name="NAAM-MAATR-DIA" type="{}NAAM-AUTOR-DIA" minOccurs="0"/>
 *         &lt;element name="REG-DAT-MAATR" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="EIND-DAT-MAATR" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="GEVORD-INL-DAT" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="GEVORD-INL-SRT" type="{}GEVORD-INL-SRT" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MAATREGEL-GEG",
    propOrder = {

    })
public class MAATREGELGEG implements Serializable {

  @XmlElement(name = "MAATR-VOLG-NR")
  private BigInteger maatrvolgnr;
  @XmlElement(name = "SRT-MAATR")
  private String     srtmaatr;
  @XmlElement(name = "SRT-AUT-MAATR")
  private String     srtautmaatr;
  @XmlElement(name = "AUTOR-C-MAATR")
  private BigInteger autorcmaatr;
  @XmlElement(name = "NAAM-AUT-MAATR")
  private String     naamautmaatr;
  @XmlElement(name = "NAAM-MAATR-DIA")
  private String     naammaatrdia;
  @XmlElement(name = "REG-DAT-MAATR")
  private BigInteger regdatmaatr;
  @XmlElement(name = "EIND-DAT-MAATR")
  private BigInteger einddatmaatr;
  @XmlElement(name = "GEVORD-INL-DAT")
  private BigInteger gevordinldat;
  @XmlElement(name = "GEVORD-INL-SRT")
  private BigInteger gevordinlsrt;

  public BigInteger getMaatrvolgnr() {
    return this.maatrvolgnr;
  }

  public void setMaatrvolgnr(BigInteger maatrvolgnr) {
    this.maatrvolgnr = maatrvolgnr;
  }

  public String getSrtmaatr() {
    return this.srtmaatr;
  }

  public void setSrtmaatr(String srtmaatr) {
    this.srtmaatr = srtmaatr;
  }

  public String getSrtautmaatr() {
    return this.srtautmaatr;
  }

  public void setSrtautmaatr(String srtautmaatr) {
    this.srtautmaatr = srtautmaatr;
  }

  public BigInteger getAutorcmaatr() {
    return this.autorcmaatr;
  }

  public void setAutorcmaatr(BigInteger autorcmaatr) {
    this.autorcmaatr = autorcmaatr;
  }

  public String getNaamautmaatr() {
    return this.naamautmaatr;
  }

  public void setNaamautmaatr(String naamautmaatr) {
    this.naamautmaatr = naamautmaatr;
  }

  public String getNaammaatrdia() {
    return this.naammaatrdia;
  }

  public void setNaammaatrdia(String naammaatrdia) {
    this.naammaatrdia = naammaatrdia;
  }

  public BigInteger getRegdatmaatr() {
    return this.regdatmaatr;
  }

  public void setRegdatmaatr(BigInteger regdatmaatr) {
    this.regdatmaatr = regdatmaatr;
  }

  public BigInteger getEinddatmaatr() {
    return this.einddatmaatr;
  }

  public void setEinddatmaatr(BigInteger einddatmaatr) {
    this.einddatmaatr = einddatmaatr;
  }

  public BigInteger getGevordinldat() {
    return this.gevordinldat;
  }

  public void setGevordinldat(BigInteger gevordinldat) {
    this.gevordinldat = gevordinldat;
  }

  public BigInteger getGevordinlsrt() {
    return this.gevordinlsrt;
  }

  public void setGevordinlsrt(BigInteger gevordinlsrt) {
    this.gevordinlsrt = gevordinlsrt;
  }

}
