/*
 * Signaleringcontroles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package nl.procura.burgerzaken.vrsclient.api;

import nl.procura.burgerzaken.vrsclient.ApiClient;
import nl.procura.burgerzaken.vrsclient.api.model.TokenRequest;
import nl.procura.burgerzaken.vrsclient.api.model.TokenResponse;

public class TokenApi {

  private final ApiClient apiClient;

  public TokenApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public TokenResponse getTokenResponse(TokenRequest tokenRequest) {
    ApiClient.Request<String> request = new ApiClient.Request("");

    StringBuilder formData = new StringBuilder();
    formData.append("grant_type=client_credentials");
    formData.append("&client_id=");
    formData.append(tokenRequest.clientId());
    formData.append("&client_secret=");
    formData.append(tokenRequest.clientSecret());
    formData.append("&scope=");
    formData.append(tokenRequest.scope());
    formData.append("&resourceServer=");
    formData.append(tokenRequest.resourceServer());
    request.body(formData.toString());

    request.header("Content-Type", "*/*");
    request.header("Accept", "application/json");
    return apiClient.post(request, TokenResponse.class);
  }
}
