---
openapi: 3.0.1
info:
  title: Signaleringcontroles API
  version: 1.29.0
servers:
  - url: http://localhost:8080
    description: Generated server url
tags:
  - name: Signalering Controller
    description: Signaleringcontroles API
paths:
  "/signaleringcontroles/v2/persoonsgegevens":
    post:
      tags:
        - Signalering Controller
      summary: Vind een persoon met signalering(en) op persoonsgegevens en Aanleiding
      description: Het resultaat van deze aanroep is 1 persoon met signalering(en)
        gevonden (HIT), geen persoon met signalering(en) gevonden (NO_HIT) of meerdere
        personen met signalering(en) gevonden (MULTIPLE_HITS)
      operationId: signaleringsRequestPersoonsGegevens
      parameters:
        - in: header
          "$ref": "#/components/parameters/pseudoniem"
        - in: header
          "$ref": "#/components/parameters/instantie_code"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignaleringRequestV2PersoonsGegevens"
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignaleringResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidationErrorMessages"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorMessage"
      security:
        - jwt-bearer-token: [ ]
  "/signaleringcontroles/v2/bsn":
    post:
      tags:
        - Signalering Controller
      summary: Vind een persoon met signalering(en) op BSN nummer en Aanleiding
      description: Het resultaat van deze aanroep is 1 persoon met signalering(en)
        gevonden (HIT) of geen persoon met signalering(en) gevonden (NO_HIT)
      operationId: signaleringsRequestBSN
      parameters:
        - in: header
          "$ref": "#/components/parameters/pseudoniem"
        - in: header
          "$ref": "#/components/parameters/instantie_code"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignaleringRequestV2Bsn"
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignaleringResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidationErrorMessages"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorMessage"
      security:
        - jwt-bearer-token: [ ]
  "/signaleringcontroles/v1/persoonsgegevens":
    post:
      tags:
        - Signalering Controller
      summary: Vind een persoon met signalering(en) op persoonsgegevens
      description: Het resultaat van deze aanroep is 1 persoon met signalering(en)
        gevonden (HIT), geen persoon met signalering(en) gevonden (NO_HIT) of meerdere
        personen met signalering(en) gevonden (MULTIPLE_HITS)
      operationId: signaleringsRequestPersoonsGegevens_1
      parameters:
        - in: header
          "$ref": "#/components/parameters/pseudoniem"
        - in: header
          "$ref": "#/components/parameters/instantie_code"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignaleringRequestV1PersoonsGegevens"
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignaleringResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidationErrorMessages"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorMessage"
      security:
        - jwt-bearer-token: [ ]
  "/signaleringcontroles/v1/bsn":
    post:
      tags:
        - Signalering Controller
      summary: Vind een persoon met signalering(en) op BSN nummer
      description: Het resultaat van deze aanroep is 1 persoon met signalering(en)
        gevonden (HIT) of geen persoon met signalering(en) gevonden (NO_HIT)
      operationId: signaleringsRequestBSN_1
      parameters:
        - in: header
          "$ref": "#/components/parameters/pseudoniem"
        - in: header
          "$ref": "#/components/parameters/instantie_code"
      requestBody:
        content:
          application/json:
            schema:
              "$ref": "#/components/schemas/SignaleringRequestV1Bsn"
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/SignaleringResponse"
        '400':
          description: Bad request
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidationErrorMessages"
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Server error
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ErrorMessage"
      security:
        - jwt-bearer-token: [ ]
components:
  schemas:
    SignaleringRequestV2PersoonsGegevens:
      required:
        - aanleiding
        - geboortedatum
        - geslachtsnaam
      type: object
      properties:
        aanleiding:
          type: string
          enum:
            - REISDOCUMENTAANVRAAG
            - IDENTITEITSONDERZOEK
        geslachtsnaam:
          maxLength: 200
          minLength: 0
          type: string
        voorvoegselGeslachtsnaam:
          maxLength: 10
          minLength: 0
          type: string
        voornamen:
          maxLength: 200
          minLength: 0
          type: string
        geboortedatum:
          pattern: yyyy-MM-dd
          type: string
          format: string
        aanvraagnummer:
          type: string
    Artikel:
      type: object
      properties:
        artikelnummer:
          type: string
        subartikel:
          type: string
        subartikelomschrijvingScherm:
          type: string
    Instantie:
      type: object
      properties:
        naam:
          type: string
    Land:
      type: object
      properties:
        code:
          type: string
        naam:
          type: string
    Persoon:
      type: object
      properties:
        bsn:
          type: string
        geslachtsnaam:
          type: string
        voorvoegselGeslachtsnaam:
          type: string
        voornamen:
          type: string
        geslacht:
          type: string
        geboortedatum:
          type: string
        geboorteplaats:
          type: string
        geboorteland:
          "$ref": "#/components/schemas/Land"
    Signalering:
      type: object
      properties:
        registratiedatum:
          type: string
          format: date
        subartikelen:
          type: array
          items:
            "$ref": "#/components/schemas/SignaleringArtikel"
        instantie:
          "$ref": "#/components/schemas/Instantie"
        zaaknummer:
          type: string
        naamContactpersoon:
          type: string
        telefoonContactpersoon:
          type: string
        emailContactpersoon:
          type: string
    SignaleringArtikel:
      type: object
      properties:
        artikel:
          "$ref": "#/components/schemas/Artikel"
    SignaleringInformatie:
      type: object
      properties:
        persoon:
          "$ref": "#/components/schemas/Persoon"
        signaleringen:
          type: array
          items:
            "$ref": "#/components/schemas/Signalering"
    SignaleringResponse:
      type: object
      properties:
        resultaatCode:
          type: string
          description: Kan de waarde HIT, NO_HIT of MULTIPLE_HITS hebben
          example: HIT
          enum:
            - HIT
            - NO_HIT
            - MULTIPLE_HITS
        resultaatOmschrijving:
          type: string
          example: Paspoortsignalering(en) voor persoon aanwezig
        mededelingRvIG:
          type: string
          description: Dit veld is alleen gevuld als de resultaatCode de waarde MUTLIPLE_HITS
            heeft
          example: Neem contact op met de Rijksdienst voor Identiteitsgegevens van
            het ministerie van Binnenlandse Zaken en Koninkrijksrelaties via het nummer
            088-9001000.
        peildatum:
          type: string
          format: date-time
        signaleringInformatie:
          "$ref": "#/components/schemas/SignaleringInformatie"
    ErrorMessage:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        tijdstip:
          type: string
          format: date-time
        titel:
          type: string
        instantie:
          type: string
    InvalidParam:
      type: object
      properties:
        code:
          type: string
        reden:
          type: string
        naam:
          type: string
    ValidationErrorMessages:
      type: object
      properties:
        status:
          type: string
        code:
          type: string
        tijdstip:
          type: string
          format: date-time
        titel:
          type: string
        instantie:
          type: string
        ongeldige-parameters:
          type: array
          items:
            "$ref": "#/components/schemas/InvalidParam"
    SignaleringRequestV2Bsn:
      required:
        - aanleiding
        - bsn
      type: object
      properties:
        aanleiding:
          type: string
          enum:
            - REISDOCUMENTAANVRAAG
            - IDENTITEITSONDERZOEK
        bsn:
          type: string
        aanvraagnummer:
          type: string
    SignaleringRequestV1PersoonsGegevens:
      required:
        - aanvraagnummer
        - geboortedatum
        - geslachtsnaam
      type: object
      properties:


        geslachtsnaam:
          maxLength: 200
          minLength: 0
          type: string
        voorvoegselGeslachtsnaam:
          maxLength: 10
          minLength: 0
          type: string
        voornamen:
          maxLength: 200
          minLength: 0
          type: string
        geboortedatum:
          pattern: yyyy-MM-dd
          type: string
          format: string
        aanvraagnummer:
          type: string
    SignaleringRequestV1Bsn:
      required:
        - aanvraagnummer
        - bsn
      type: object
      properties:


        bsn:
          type: string
        aanvraagnummer:
          type: string
  parameters:
    pseudoniem:
      name: pseudoniem
      in: header
      description: gebruiker pseudoniem
      schema:
        type: string
    instantie_code:
      name: instantie_code
      in: header
      description: gebruiker instantie code
      schema:
        type: string
  securitySchemes:
    jwt-bearer-token:
      type: http
      scheme: bearer
      bearerFormat: JWT
