/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:23 PM CEST 
//

package nl.procura.rdw.processen.p0184.f08;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for RYB-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RYB-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="RYB-NR" type="{}RYB-NR" minOccurs="0"/>
 *         &lt;element name="AFGIFTE-DAT-RYB" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="SRT-AUT-AFG" type="{}SOORT-AUTOR" minOccurs="0"/>
 *         &lt;element name="AUTOR-CODE-AFG" type="{}AUTOR-CODE-AFG" minOccurs="0"/>
 *         &lt;element name="NAAM-AUT-AFG" type="{}NAAM-AUTOR" minOccurs="0"/>
 *         &lt;element name="NAAM-AFG-DIA" type="{}NAAM-AUTOR-DIA" minOccurs="0"/>
 *         &lt;element name="SRT-AUT-VERL-D" type="{}SOORT-AUTOR" minOccurs="0"/>
 *         &lt;element name="AUTOR-C-VERL-D" type="{}AUTOR-CODE-RYB" minOccurs="0"/>
 *         &lt;element name="NAAM-AUT-VERL-D" type="{}NAAM-AUTOR" minOccurs="0"/>
 *         &lt;element name="NAAM-VERL-D-DIA" type="{}NAAM-AUTOR-DIA" minOccurs="0"/>
 *         &lt;element name="VERL-DIEFST-DAT" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="PROC-V-VERL-D" type="{}PROC-VERBAAL-NR" minOccurs="0"/>
 *         &lt;element name="VERVANG-RYB-NR" type="{}RYB-NR-LANG" minOccurs="0"/>
 *         &lt;element name="ERK-RYB-NR" type="{}RYB-NR-LANG" minOccurs="0"/>
 *         &lt;element name="ERK-RYB-DAT" type="{}DATUM-EJMD" minOccurs="0"/>
 *         &lt;element name="LAND-CODE-ERK" type="{}LAND-CODE" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RYB-GEG",
    propOrder = {

    })
public class RYBGEG implements Serializable {

  @XmlElement(name = "RYB-NR")
  private BigInteger rybnr;
  @XmlElement(name = "AFGIFTE-DAT-RYB")
  private BigInteger afgiftedatryb;
  @XmlElement(name = "SRT-AUT-AFG")
  private String     srtautafg;
  @XmlElement(name = "AUTOR-CODE-AFG")
  private BigInteger autorcodeafg;
  @XmlElement(name = "NAAM-AUT-AFG")
  private String     naamautafg;
  @XmlElement(name = "NAAM-AFG-DIA")
  private String     naamafgdia;
  @XmlElement(name = "SRT-AUT-VERL-D")
  private String     srtautverld;
  @XmlElement(name = "AUTOR-C-VERL-D")
  private BigInteger autorcverld;
  @XmlElement(name = "NAAM-AUT-VERL-D")
  private String     naamautverld;
  @XmlElement(name = "NAAM-VERL-D-DIA")
  private String     naamverlddia;
  @XmlElement(name = "VERL-DIEFST-DAT")
  private BigInteger verldiefstdat;
  @XmlElement(name = "PROC-V-VERL-D")
  private String     procvverld;
  @XmlElement(name = "VERVANG-RYB-NR")
  private String     vervangrybnr;
  @XmlElement(name = "ERK-RYB-NR")
  private String     erkrybnr;
  @XmlElement(name = "ERK-RYB-DAT")
  private BigInteger erkrybdat;
  @XmlElement(name = "LAND-CODE-ERK")
  private BigInteger landcodeerk;

  public BigInteger getRybnr() {
    return this.rybnr;
  }

  public void setRybnr(BigInteger rybnr) {
    this.rybnr = rybnr;
  }

  public BigInteger getAfgiftedatryb() {
    return this.afgiftedatryb;
  }

  public void setAfgiftedatryb(BigInteger afgiftedatryb) {
    this.afgiftedatryb = afgiftedatryb;
  }

  public String getSrtautafg() {
    return this.srtautafg;
  }

  public void setSrtautafg(String srtautafg) {
    this.srtautafg = srtautafg;
  }

  public BigInteger getAutorcodeafg() {
    return this.autorcodeafg;
  }

  public void setAutorcodeafg(BigInteger autorcodeafg) {
    this.autorcodeafg = autorcodeafg;
  }

  public String getNaamautafg() {
    return this.naamautafg;
  }

  public void setNaamautafg(String naamautafg) {
    this.naamautafg = naamautafg;
  }

  public String getNaamafgdia() {
    return this.naamafgdia;
  }

  public void setNaamafgdia(String naamafgdia) {
    this.naamafgdia = naamafgdia;
  }

  public String getSrtautverld() {
    return this.srtautverld;
  }

  public void setSrtautverld(String srtautverld) {
    this.srtautverld = srtautverld;
  }

  public BigInteger getAutorcverld() {
    return this.autorcverld;
  }

  public void setAutorcverld(BigInteger autorcverld) {
    this.autorcverld = autorcverld;
  }

  public String getNaamautverld() {
    return this.naamautverld;
  }

  public void setNaamautverld(String naamautverld) {
    this.naamautverld = naamautverld;
  }

  public String getNaamverlddia() {
    return this.naamverlddia;
  }

  public void setNaamverlddia(String naamverlddia) {
    this.naamverlddia = naamverlddia;
  }

  public BigInteger getVerldiefstdat() {
    return this.verldiefstdat;
  }

  public void setVerldiefstdat(BigInteger verldiefstdat) {
    this.verldiefstdat = verldiefstdat;
  }

  public String getProcvverld() {
    return this.procvverld;
  }

  public void setProcvverld(String procvverld) {
    this.procvverld = procvverld;
  }

  public String getVervangrybnr() {
    return this.vervangrybnr;
  }

  public void setVervangrybnr(String vervangrybnr) {
    this.vervangrybnr = vervangrybnr;
  }

  public String getErkrybnr() {
    return this.erkrybnr;
  }

  public void setErkrybnr(String erkrybnr) {
    this.erkrybnr = erkrybnr;
  }

  public BigInteger getErkrybdat() {
    return this.erkrybdat;
  }

  public void setErkrybdat(BigInteger erkrybdat) {
    this.erkrybdat = erkrybdat;
  }

  public BigInteger getLandcodeerk() {
    return this.landcodeerk;
  }

  public void setLandcodeerk(BigInteger landcodeerk) {
    this.landcodeerk = landcodeerk;
  }

}
