### Zoek op alle zaakgegevens
POST http://{{host}}:{{port}}/personen/rest/v2/zaken/toevoegen
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "zaak": {
    "algemeen": {
      "zaakId": "lijkv-1234",
      "type": "LIJKVINDING",
      "status": "INCOMPLEET",
      "bron": "SIM-APP",
      "leverancier": "SIM",
      "datumIngang": 20200430,
      "datumInvoer": 20200428,
      "tijdInvoer": 101112
    },
    "overlijden": {
      "lijkvinding": {
        "overledene": {
          "bsn": 999994335,
          "voornamen": "Madonna",
          "geslachtsnaam": "Kaart",
          "voorvoegsel": "van der",
          "titelPredikaat": "JV",
          "geboortedatum": 19750307,
          "geboorteplaats": {
            "waarde": "0548",
            "omschrijving": "Leidschendam"
          },
          "geboorteland": {
            "waarde": "6030",
            "omschrijving": "Nederland"
          },
          "contactgegevens": {
            "email": "moeder@procura.nl",
            "telefoonThuis": "11111",
            "telefoonWerk": "22222",
            "telefoonMobiel": "3333",
            "telefoonBuitenland": {
              "telefoon": "4444",
              "landCode": 5010
            }
          }
        },
        "aangifte": {
          "schriftelijkeAangever": "OFFICIER_VAN_JUSTITIE",
          "plaats": {
            "waarde": "0398",
            "omschrijving": "Heerhugowaard"
          },
          "datum": 20200816,
          "tijd": 110000,
          "toevoeging": "Gevonden thuis in een stoel",
          "documentType": "NIET_NATUURLIJK_DOOD"
        },
        "lijkbezorging": {
          "datum": 20201030,
          "tijd": 130000,
          "lijkbezorgingType": "BEGRAVING_CREMATIE",
          "buitenBenelux": true,
          "doodsoorzaakType": "NON_CONTAGIOUS_DISEASE",
          "landVanBestemming": {
            "waarde": "8045",
            "omschrijving": "Antigua en Barbuda"
          },
          "plaatsVanBestemming": "Timboektoe",
          "via": "Het vliegveld",
          "vervoermiddel": "Vliegtuig"
        },
        "verzoek": {
          "correspondentie": {
            "type": "POST",
            "organisatie": "Procura B.V.",
            "afdeling": "Burgerzaken",
            "naam": "Dhr. F. Janssen",
            "email": "test@procura.nl",
            "telefoon": "123456",
            "straat": "Parelweg",
            "hnr": 12,
            "hnrL": "A",
            "hnrT": "TO",
            "postcode": "1821RS",
            "plaats": "Alkmaar"
          },
          "uittreksels": [
            {
              "code": "akte1",
              "omschrijving": "Mooie uitt1",
              "aantal": 1
            },
            {
              "code": "akte2",
              "omschrijving": "Mooie uitt2",
              "aantal": 1
            }
          ]
        }
      }
    }
  }
}

###