POST http://{{host}}:{{port}}/personen/rest/v2/zaken/toevoegen
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "zaak": {
    "algemeen": {
      "zaakId": null,
      "meestRelevanteZaakId": null,
      "type": "HUWELIJK_GPS_GEMEENTE",
      "soort": null,
      "omschrijving": null,
      "status": "OPGENOMEN",
      "bron": "E-loket",
      "leverancier": "Procura",
      "datumIngang": 20190101,
      "datumInvoer": 20200612,
      "tijdInvoer": 124324,
      "locatieInvoer": null,
      "gebruikerInvoer": null,
      "ids": [
        {
          "id": "commitment-1234",
          "systeem": "ZAAKSYSTEEM"
        }
      ],
      "statussen": null,
      "extraAttributen": null,
      "gekoppeldeZaken": null
    },
    "verhuizing": null,
    "geboorte": null,
    "erkenning": null,
    "huwelijk": {
      "partner1": {
        "persoon": {
          "bsn": 1351,
          "contactgegevens": {
            "email": "partner1@procura.nl",
            "telefoonThuis": "31654322345",
            "telefoonWerk": null,
            "telefoonMobiel": null,
            "telefoonBuitenland": null
          }
        },
        "naamgebruik": {
          "type": "V",
          "geslachtsnaam": "Vries",
          "titelPredikaat": "B",
          "voorvoegsel": "de"
        }
      },
      "partner2": {
        "persoon": {
          "bsn": 999994335,
          "contactgegevens": {
            "email": "burgerzaken@procura.nl",
            "telefoonThuis": "0887708100",
            "telefoonWerk": null,
            "telefoonMobiel": null,
            "telefoonBuitenland": null
          }
        },
        "naamgebruik": {
          "type": "N",
          "geslachtsnaam": "Jansen",
          "titelPredikaat": "JV",
          "voorvoegsel": null
        }
      },
      "planning": {
        "soort": "HUWELIJK",
        "datumVoornemen": 20200401,
        "datumVerbintenis": 20200607,
        "tijdVerbintenis": 80910,
        "toelichting": "Nice Wedding!"
      },
      "locatie": {
        "naam": "Het Generaalshuis (Theater aan het Vrijthof)",
        "aliassen": [
          "generaalshuis"
        ],
        "opties": [
          {
            "type": "TEKST",
            "naam": "Taalceremonie",
            "aliassen": [
              "taal_ceremonie"
            ],
            "waarde": "Spaans",
            "omschrijving": "Taalceremonie"
          },
          {
            "type": "NUMMER",
            "naam": "Max. aantal personen",
            "aliassen": [
              "max_personen",
              "max.aantal.personen"
            ],
            "waarde": "75",
            "omschrijving": "Max. aantal personen (1 - 250"
          },
          {
            "type": "BOOLEAN",
            "naam": "Trouwboekje/Partnerschapsboekje",
            "aliassen": [
              "trouwboekje"
            ],
            "waarde": "true",
            "omschrijving": "Trouwboekje/Partnerschapsboekje"
          }
        ]
      },
      "getuigen": {
        "aantalGemeenteGetuigen": 2,
        "eigenGetuigen": [
          {
            "persoon": {
              "bsn": null,
              "voornamen": "Firstname 1",
              "geslachtsnaam": "Lastname 1",
              "voorvoegsel": null,
              "titelPredikaat": null,
              "geboortedatum": 20041210,
              "toelichting": "Witness 1"
            }
          },
          {
            "persoon": {
              "bsn": 999990019,
              "toelichting": "Witness 2"
            }
          }
        ]
      },
      "ambtenaren": {
        "voorkeuren": [
          {
            "naam": null,
            "telefoon": null,
            "email": null,
            "aliassen": [
              "marco"
            ]
          }
        ],
        "toegekend": null
      }
    }
  }
}

###