### Zoek op alle zaakgegevens
POST http://{{host}}:{{port}}/personen/rest/v2/zaken/toevoegen
Accept: application/json
Content-Type: application/json
Authorization: Basic {{username}} {{password}}

{
  "zaak": {
    "algemeen": {
      "zaakId": "test-1234",
      "type": "GEBOORTE",
      "status": "INCOMPLEET",
      "bron": "SIM-APP",
      "leverancier": "SIM",
      "datumIngang": 20200430,
      "datumInvoer": 20200428,
      "tijdInvoer": 101112
    },
    "geboorte": {
      "aangever": {
        "bsn": 1351,
        "contactgegevens": {
          "email": "aangever@procura.nl",
          "telefoonThuis": "5555",
          "telefoonWerk": "6666",
          "telefoonMobiel": "7777",
          "telefoonBuitenland": {
            "telefoon": "8888",
            "landCode": 5010
          }
        }
      },
      "moeder": {
        "bsn": 999994335,
        "contactgegevens": {
          "email": "moeder@procura.nl",
          "telefoonThuis": "11111",
          "telefoonWerk": "22222",
          "telefoonMobiel": "3333",
          "telefoonBuitenland": {
            "telefoon": "4444",
            "landCode": 5010
          }
        }
      },
      "kinderen": [
        {
          "voornamen": "Piet",
          "geslacht": "MAN",
          "geboortedatum": 20200429,
          "geboortetijd": 101112
        },
        {
          "voornamen": "Truus",
          "geslacht": "VROUW",
          "geboortedatum": 20200429,
          "geboortetijd": 1430
        }
      ],
      "verzoek": {
        "vaderOfDuoMoeder": {
          "bsn": 695108608
        },
        "geslachtsnaam": "Geld",
        "voorvoegsel": "van der",
        "titelPredikaat": "JV"
      }
    }
  }
}

###