/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:23 PM CEST 
//

package nl.procura.rdw.processen.p0183.f08;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for VERBLYF-RYB-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="VERBLYF-RYB-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="ONTV-RYB-DAT" type="{}DATUM-EJMD"/>
 *         &lt;element name="ONTV-RYB-TYD" type="{}TYD-UM"/>
 *         &lt;element name="AUTOR-CODE-ONTV" type="{}AUTOR-CODE-RYB" minOccurs="0"/>
 *         &lt;element name="KORPS-CODE-ONTV" type="{}KORPS-CODE" minOccurs="0"/>
 *         &lt;element name="AUTOR-CODE-VERZ" type="{}AUTOR-CODE-RYB" minOccurs="0"/>
 *         &lt;element name="KORPS-CODE-VERZ" type="{}KORPS-CODE" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "VERBLYF-RYB-GEG",
    propOrder = {

    })
public class VERBLYFRYBGEG implements Serializable {

  @XmlElement(name = "ONTV-RYB-DAT",
      required = true)
  private BigInteger ontvrybdat;
  @XmlElement(name = "ONTV-RYB-TYD",
      required = true)
  private BigInteger ontvrybtyd;
  @XmlElement(name = "AUTOR-CODE-ONTV")
  private BigInteger autorcodeontv;
  @XmlElement(name = "KORPS-CODE-ONTV")
  private String     korpscodeontv;
  @XmlElement(name = "AUTOR-CODE-VERZ")
  private BigInteger autorcodeverz;
  @XmlElement(name = "KORPS-CODE-VERZ")
  private String     korpscodeverz;

  public BigInteger getOntvrybdat() {
    return this.ontvrybdat;
  }

  public void setOntvrybdat(BigInteger ontvrybdat) {
    this.ontvrybdat = ontvrybdat;
  }

  public BigInteger getOntvrybtyd() {
    return this.ontvrybtyd;
  }

  public void setOntvrybtyd(BigInteger ontvrybtyd) {
    this.ontvrybtyd = ontvrybtyd;
  }

  public BigInteger getAutorcodeontv() {
    return this.autorcodeontv;
  }

  public void setAutorcodeontv(BigInteger autorcodeontv) {
    this.autorcodeontv = autorcodeontv;
  }

  public String getKorpscodeontv() {
    return this.korpscodeontv;
  }

  public void setKorpscodeontv(String korpscodeontv) {
    this.korpscodeontv = korpscodeontv;
  }

  public BigInteger getAutorcodeverz() {
    return this.autorcodeverz;
  }

  public void setAutorcodeverz(BigInteger autorcodeverz) {
    this.autorcodeverz = autorcodeverz;
  }

  public String getKorpscodeverz() {
    return this.korpscodeverz;
  }

  public void setKorpscodeverz(String korpscodeverz) {
    this.korpscodeverz = korpscodeverz;
  }

}
