/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:28 PM CEST 
//

package nl.procura.rdw.processen.p0252.f07;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each
 * Java content interface and Java element interface
 * generated in the nl.procura.rdw.processen.p0252.f07 package.
 * <p>An ObjectFactory allows you to programatically
 * construct new instances of the Java representation
 * for XML content. The Java representation of XML
 * content can consist of schema derived interfaces
 * and classes representing the binding of schema
 * type definitions, element declarations and model
 * groups.  Factory methods for each of these are
 * provided in this class.
 */
@XmlRegistry
public class ObjectFactory {

  private final static QName _NATPRYBMAATR_QNAME = new QName("", "NAT-P-RYB-MAATR");

  /**
   * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: nl.procura.rdw.processen.p0252.f07
   */
  public ObjectFactory() {
  }

  /**
   * Create an instance of {@link NATPRYBMAATR }
   */
  public NATPRYBMAATR createNATPRYBMAATR() {
    return new NATPRYBMAATR();
  }

  /**
   * Create an instance of {@link UITGMAATRTAB }
   */
  public UITGMAATRTAB createUITGMAATRTAB() {
    return new UITGMAATRTAB();
  }

  /**
   * Create an instance of {@link ONTZEGPERGEG }
   */
  public ONTZEGPERGEG createONTZEGPERGEG() {
    return new ONTZEGPERGEG();
  }

  /**
   * Create an instance of {@link INHOUDPERGEG }
   */
  public INHOUDPERGEG createINHOUDPERGEG() {
    return new INHOUDPERGEG();
  }

  /**
   * Create an instance of {@link STRAFMAATRGEG }
   */
  public STRAFMAATRGEG createSTRAFMAATRGEG() {
    return new STRAFMAATRGEG();
  }

  /**
   * Create an instance of {@link ONGVERKLGEG }
   */
  public ONGVERKLGEG createONGVERKLGEG() {
    return new ONGVERKLGEG();
  }

  /**
   * Create an instance of {@link MAATREGELGEG }
   */
  public MAATREGELGEG createMAATREGELGEG() {
    return new MAATREGELGEG();
  }

  /**
   * Create an instance of {@link VORDPROCGEG }
   */
  public VORDPROCGEG createVORDPROCGEG() {
    return new VORDPROCGEG();
  }

  /**
   * Create an instance of {@link UITGMAATRGEG }
   */
  public UITGMAATRGEG createUITGMAATRGEG() {
    return new UITGMAATRGEG();
  }

  /**
   * Create an instance of {@link ONGELDCATGEG }
   */
  public ONGELDCATGEG createONGELDCATGEG() {
    return new ONGELDCATGEG();
  }

  /**
   * Create an instance of {@link INNEMPERGEG }
   */
  public INNEMPERGEG createINNEMPERGEG() {
    return new INNEMPERGEG();
  }

  /**
   * Create an instance of {@link NATPZOEKGEG }
   */
  public NATPZOEKGEG createNATPZOEKGEG() {
    return new NATPZOEKGEG();
  }

  /**
   * Create an instance of {@link INNEMPERTAB }
   */
  public INNEMPERTAB createINNEMPERTAB() {
    return new INNEMPERTAB();
  }

  /**
   * Create an instance of {@link ONTZEGPERTAB }
   */
  public ONTZEGPERTAB createONTZEGPERTAB() {
    return new ONTZEGPERTAB();
  }

  /**
   * Create an instance of {@link INNEMRYBGEG }
   */
  public INNEMRYBGEG createINNEMRYBGEG() {
    return new INNEMRYBGEG();
  }

  /**
   * Create an instance of {@link INHOUDPERTAB }
   */
  public INHOUDPERTAB createINHOUDPERTAB() {
    return new INHOUDPERTAB();
  }

  /**
   * Create an instance of {@link ALGGEG }
   */
  public ALGGEG createALGGEG() {
    return new ALGGEG();
  }

  /**
   * Create an instance of {@link ONGELDCATTAB }
   */
  public ONGELDCATTAB createONGELDCATTAB() {
    return new ONGELDCATTAB();
  }

  /**
   * Create an instance of {@link JAXBElement }{@code <}{@link NATPRYBMAATR }{@code >}}
   */
  @XmlElementDecl(namespace = "",
      name = "NAT-P-RYB-MAATR")
  public JAXBElement<NATPRYBMAATR> createNATPRYBMAATR(NATPRYBMAATR value) {
    return new JAXBElement<>(_NATPRYBMAATR_QNAME, NATPRYBMAATR.class, null, value);
  }

}
