/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:30 PM CEST 
//

package nl.procura.rdw.processen.p1659.f02;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for RYV-VERKL-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="RYV-VERKL-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="AFG-DAT-R-VERKL" type="{}DATUM-EJMD"/>
 *         &lt;element name="STATUS-R-VERKL" type="{}STATUS-R-VERKL"/>
 *         &lt;element name="TOEL-BL-R-VERKL" type="{}TOEL-BLOKKERING" minOccurs="0"/>
 *         &lt;element name="AUT-IND-R-VERKL" type="{}INDIC-JN" minOccurs="0"/>
 *         &lt;element name="CAT-BEPERK-IND" type="{}INDIC-JN" minOccurs="0"/>
 *         &lt;element name="SRT-LEG-R-VERKL" type="{}SOORT-LEGITIM" minOccurs="0"/>
 *         &lt;element name="LEG-NR-R-VERKL" type="{}LEGITIM-NR" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RYV-VERKL-GEG",
    propOrder = {

    })
public class RYVVERKLGEG implements Serializable {

  @XmlElement(name = "AFG-DAT-R-VERKL",
      required = true)
  private BigInteger afgdatrverkl;
  @XmlElement(name = "STATUS-R-VERKL",
      required = true)
  private String     statusrverkl;
  @XmlElement(name = "TOEL-BL-R-VERKL")
  private String     toelblrverkl;
  @XmlElement(name = "AUT-IND-R-VERKL")
  private String     autindrverkl;
  @XmlElement(name = "CAT-BEPERK-IND")
  private String     catbeperkind;
  @XmlElement(name = "SRT-LEG-R-VERKL")
  private String     srtlegrverkl;
  @XmlElement(name = "LEG-NR-R-VERKL")
  private String     legnrrverkl;

  public BigInteger getAfgdatrverkl() {
    return this.afgdatrverkl;
  }

  public void setAfgdatrverkl(BigInteger afgdatrverkl) {
    this.afgdatrverkl = afgdatrverkl;
  }

  public String getStatusrverkl() {
    return this.statusrverkl;
  }

  public void setStatusrverkl(String statusrverkl) {
    this.statusrverkl = statusrverkl;
  }

  public String getToelblrverkl() {
    return this.toelblrverkl;
  }

  public void setToelblrverkl(String toelblrverkl) {
    this.toelblrverkl = toelblrverkl;
  }

  public String getAutindrverkl() {
    return this.autindrverkl;
  }

  public void setAutindrverkl(String autindrverkl) {
    this.autindrverkl = autindrverkl;
  }

  public String getCatbeperkind() {
    return this.catbeperkind;
  }

  public void setCatbeperkind(String catbeperkind) {
    this.catbeperkind = catbeperkind;
  }

  public String getSrtlegrverkl() {
    return this.srtlegrverkl;
  }

  public void setSrtlegrverkl(String srtlegrverkl) {
    this.srtlegrverkl = srtlegrverkl;
  }

  public String getLegnrrverkl() {
    return this.legnrrverkl;
  }

  public void setLegnrrverkl(String legnrrverkl) {
    this.legnrrverkl = legnrrverkl;
  }

}
