/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:31 PM CEST 
//

package nl.procura.rdw.processen.p1914.f02;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for NAT-P-AANVR-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NAT-P-AANVR-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="NAT-PERSOON-GEG" type="{}NAT-PERSOON-GEG"/>
 *         &lt;element name="AANVR-RYB-K-GEG" type="{}AANVR-RYB-K-GEG"/>
 *         &lt;element name="STAT-RYB-K-GEG" type="{}STAT-RYB-K-GEG"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAT-P-AANVR-GEG",
    propOrder = {

    })
public class NATPAANVRGEG implements Serializable {

  @XmlElement(name = "NAT-PERSOON-GEG",
      required = true)
  private NATPERSOONGEG natpersoongeg;
  @XmlElement(name = "AANVR-RYB-K-GEG",
      required = true)
  private AANVRRYBKGEG  aanvrrybkgeg;
  @XmlElement(name = "STAT-RYB-K-GEG",
      required = true)
  private STATRYBKGEG   statrybkgeg;

  public NATPERSOONGEG getNatpersoongeg() {
    return this.natpersoongeg;
  }

  public void setNatpersoongeg(NATPERSOONGEG natpersoongeg) {
    this.natpersoongeg = natpersoongeg;
  }

  public AANVRRYBKGEG getAanvrrybkgeg() {
    return this.aanvrrybkgeg;
  }

  public void setAanvrrybkgeg(AANVRRYBKGEG aanvrrybkgeg) {
    this.aanvrrybkgeg = aanvrrybkgeg;
  }

  public STATRYBKGEG getStatrybkgeg() {
    return this.statrybkgeg;
  }

  public void setStatrybkgeg(STATRYBKGEG statrybkgeg) {
    this.statrybkgeg = statrybkgeg;
  }

}
