/*
 * Copyright 2024 - 2025 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

/*
 * Signaleringcontroles API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package nl.procura.burgerzaken.requestinbox.api;

import java.util.Base64;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

public class TokenApi {

  private final ApiClient apiClient;

  public TokenApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  public String getToken(TokenRequest tokenRequest) {
    ApiClient.Request<TokenRequest> request = new ApiClient.Request<>("/auth");
    request.body(tokenRequest);
    request.header("Content-Type", "application/json");
    request.header("Accept", "application/json");
    String basicAuth = tokenRequest.getUsername() + ":" + tokenRequest.getPassword();
    request.header("Authorization", "Basic " + Base64.getEncoder().encodeToString(basicAuth.getBytes()));
    return apiClient.get(request, TokenResponse.class).getToken();
  }

  @Data
  @AllArgsConstructor
  public static class TokenRequest {

    private final String username;
    private final String password;
  }

  @Data
  @NoArgsConstructor
  public static class TokenResponse {

    private String token;
  }
}
