/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:28 PM CEST 
//

package nl.procura.rdw.processen.p1651.f09;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for NAT-PERSOON-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="NAT-PERSOON-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="NAT-PERS-SL" type="{}NAT-PERS-SL" minOccurs="0"/>
 *         &lt;element name="GBA-NR-NAT-P" type="{}GBA-NR" minOccurs="0"/>
 *         &lt;element name="FISC-NR-NAT-P" type="{}FISC-NR-NAT-P" minOccurs="0"/>
 *         &lt;element name="GESL-NAAM-NAT-P" type="{}GESL-NAAM" minOccurs="0"/>
 *         &lt;element name="VOOR-LET-NAT-P" type="{}VOOR-LET" minOccurs="0"/>
 *         &lt;element name="GEB-DAT-NAT-P" type="{}DATUM-EJMD" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "NAT-PERSOON-GEG",
    propOrder = {

    })
public class NATPERSOONGEG implements Serializable {

  @XmlElement(name = "NAT-PERS-SL")
  private String     natperssl;
  @XmlElement(name = "GBA-NR-NAT-P")
  private BigInteger gbanrnatp;
  @XmlElement(name = "FISC-NR-NAT-P")
  private BigInteger fiscnrnatp;
  @XmlElement(name = "GESL-NAAM-NAT-P")
  private String     geslnaamnatp;
  @XmlElement(name = "VOOR-LET-NAT-P")
  private String     voorletnatp;
  @XmlElement(name = "GEB-DAT-NAT-P")
  private BigInteger gebdatnatp;

  public String getNatperssl() {
    return this.natperssl;
  }

  public void setNatperssl(String natperssl) {
    this.natperssl = natperssl;
  }

  public BigInteger getGbanrnatp() {
    return this.gbanrnatp;
  }

  public void setGbanrnatp(BigInteger gbanrnatp) {
    this.gbanrnatp = gbanrnatp;
  }

  public BigInteger getFiscnrnatp() {
    return this.fiscnrnatp;
  }

  public void setFiscnrnatp(BigInteger fiscnrnatp) {
    this.fiscnrnatp = fiscnrnatp;
  }

  public String getGeslnaamnatp() {
    return this.geslnaamnatp;
  }

  public void setGeslnaamnatp(String geslnaamnatp) {
    this.geslnaamnatp = geslnaamnatp;
  }

  public String getVoorletnatp() {
    return this.voorletnatp;
  }

  public void setVoorletnatp(String voorletnatp) {
    this.voorletnatp = voorletnatp;
  }

  public BigInteger getGebdatnatp() {
    return this.gebdatnatp;
  }

  public void setGebdatnatp(BigInteger gebdatnatp) {
    this.gebdatnatp = gebdatnatp;
  }

}
