/*
 * Copyright 2021 - 2022 Procura B.V.
 *
 * In licentie gegeven krachtens de EUPL, versie 1.2
 * U mag dit werk niet gebruiken, behalve onder de voorwaarden van de licentie.
 * U kunt een kopie van de licentie vinden op:
 *
 *   https://github.com/vrijBRP/vrijBRP/blob/master/LICENSE.md
 *
 * Deze bevat zowel de Nederlandse als de Engelse tekst
 *
 * Tenzij dit op grond van toepasselijk recht vereist is of schriftelijk
 * is overeengekomen, wordt software krachtens deze licentie verspreid
 * "zoals deze is", ZONDER ENIGE GARANTIES OF VOORWAARDEN, noch expliciet
 * noch impliciet.
 * Zie de licentie voor de specifieke bepalingen voor toestemmingen en
 * beperkingen op grond van de licentie.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.26 at 02:32:29 PM CEST 
//

package nl.procura.rdw.processen.p1652.f01;

import java.io.Serializable;
import java.math.BigInteger;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for PERS-ZOEK-GEG complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="PERS-ZOEK-GEG">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="GESL-NAAM-NP-A" type="{}GESL-NAAM-NP"/>
 *         &lt;element name="VOOR-NAAM-NP-A" type="{}VOOR-NAAM" minOccurs="0"/>
 *         &lt;element name="VOOR-LET-NP-A" type="{}VOORLETTERS" minOccurs="0"/>
 *         &lt;element name="GEB-DAT-NP-A" type="{}DATUM-EJMD"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PERS-ZOEK-GEG",
    propOrder = {

    })
public class PERSZOEKGEG implements Serializable {

  @XmlElement(name = "GESL-NAAM-NP-A",
      required = true)
  private String     geslnaamnpa;
  @XmlElement(name = "VOOR-NAAM-NP-A")
  private String     voornaamnpa;
  @XmlElement(name = "VOOR-LET-NP-A")
  private String     voorletnpa;
  @XmlElement(name = "GEB-DAT-NP-A",
      required = true)
  private BigInteger gebdatnpa;

  public String getGeslnaamnpa() {
    return this.geslnaamnpa;
  }

  public void setGeslnaamnpa(String geslnaamnpa) {
    this.geslnaamnpa = geslnaamnpa;
  }

  public String getVoornaamnpa() {
    return this.voornaamnpa;
  }

  public void setVoornaamnpa(String voornaamnpa) {
    this.voornaamnpa = voornaamnpa;
  }

  public String getVoorletnpa() {
    return this.voorletnpa;
  }

  public void setVoorletnpa(String voorletnpa) {
    this.voorletnpa = voorletnpa;
  }

  public BigInteger getGebdatnpa() {
    return this.gebdatnpa;
  }

  public void setGebdatnpa(BigInteger gebdatnpa) {
    this.gebdatnpa = gebdatnpa;
  }

}
